#Permalinks
permalink:           pretty

# Setup
title:               Brett Anderson
tagline:             Applicant
url:                 http://bluellama.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Brett Anderson
  url:               http://bluellama.github.io
  email:             brett.anderson@gmail.com
  phone:	     512-775-6896

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
